### ISSUE TITLE
Visible parts on charts with visibility:hidden

### ISSUE THREAD

**Issue by smokir** [highcharts/highcharts#10220]
#### Expected behaviour
Hide everything

#### Actual behaviour
Pie chart
![2019-02-27 13 09 07](https://user-images.githubusercontent.com/2204174/53482714-ebf64e00-3a90-11e9-9736-c3e778a907c5.png)
Chart with plotBand
![2019-02-27 15 43 49](https://user-images.githubusercontent.com/2204174/53491085-82813a00-3aa6-11e9-9256-fc6735e3189d.png)

#### Live demo with steps to reproduce
Pie chart https://jsfiddle.net/kbmdvujr/
Chart with plotBand https://jsfiddle.net/7mfsro23/

#### Product version
Highcharts 7.0.3

#### Affected browser(s)
Yandex Browser 19.1.1.907
Chromium 72.0.3626.119
FF 64.0.2, 65.0.1

#### Not affected browser(s)
Safari 12.0.3

**Comment by KacperMadej** [comment]
Hi @smokir 

Thank you for reporting about the problem.

As a workaround you could change `display` CSS option of the chart's SVG to `none`.

```css
#container {
  border: 1px solid black;
  min-width: 300px;
  max-width: 800px;
  height: 300px;
  margin: 1em auto;
}

.highcharts-root {
  display: none;
}
```

_Internal note:_
Internally opacity could be used instead of visibility.
