### ISSUE TITLE
'highcharts-tooltip-header' class missing for the tooltip header

### ISSUE THREAD

**Issue by AntonyJos** [highcharts/highcharts#11650]
#### Expected behaviour
Expecting a default class 'highcharts-tooltip-header' for the tooltip

#### Actual behaviour
Not able to differentiate the Tooltip Header from the other series tooltips

#### Live demo with steps to reproduce

1. Hit the url https://jsfiddle.net/289e40xy/ with highstock v6.2.0
2. Try Removing the callout rendered in svg using 

```
g.highcharts-tooltip-header>path{
    fill: transparent !important;
    stroke-width: 0px !important;
}
```
3. As useHTML set to true , add styles to the haeder

```
.highcharts-tooltip-header>span{
    border: 2px solid darkgrey;
    height: 25px;
    border-radius: 6px;
    background: blue;
    color:yellow !important;
}
```
4. Add the same set of classes in v7.1.2..It doesnt seem to work

_Observation_

In v7.1.2, https://jsfiddle.net/6mgyscnj/ -> Styles are not getting affected

![style not affected](https://user-images.githubusercontent.com/42953694/62793754-f745af00-baef-11e9-8351-8a2b2e9a2494.png)

In v6.2.0, https://jsfiddle.net/289e40xy/1/ -> Styles are getting affected

![styles getting affected](https://user-images.githubusercontent.com/42953694/62793851-3a078700-baf0-11e9-9fff-1ec0f28d08b1.PNG)

#### Product version

Tested out in v6.2.0 > class 'highcharts-tooltip-header' is present
Tested out in v7.1.2 > class 'highcharts-tooltip-header' is missing

#### Affected browser(s)
Charome v72

**Comment by AntonyJos** [comment]
Also, Please let me if there is a workaround to remove the callout rendered in svg only for the tooltip header

**Comment by pawelfus** [comment]
Thanks for reporting the issue @AntonyJos 

**Workaround:**
Use path:
`.highcharts-tooltip .highcharts-label:first-child>span` instead of `.highcharts-tooltip-header>path`. Demo: https://jsfiddle.net/BlackLabel/vxbz9p0k/

Snippet:
```css
g.highcharts-tooltip .highcharts-label:first-child>path {
    fill: transparent !important;
    stroke-width: 0px !important;
}
.highcharts-tooltip .highcharts-label:first-child>span {
    border: 2px solid darkgrey;
    height: 25px;
    border-radius: 6px;
    background: blue;
    color:yellow !important;
}
```

*Internal note:*
Marking as regression, most probably after e622dddfad8a6fba4985aa87b31670f8e7cd1b49
