### ISSUE TITLE
Windows high contrast mode in new Edge browser results in non readable labels

### ISSUE THREAD

**Issue by bre1470** [highcharts/highcharts#12812]
#### Expected behaviour

The chart labels should be readable in Windows high contrast mode.

#### Actual behaviour

The chart labels are rendered white on a white background.

#### Live demo with steps to reproduce

https://jsfiddle.net/Lokesh56/g279kqcf/20/

#### Product version

all, tested with Highcharts v8.0

#### Affected browser(s)

Edge v79.0.309.68

#### Workarounds

Turn off chart background: https://jsfiddle.net/Lag8xtkh/
Move chart background to SVG root: https://jsfiddle.net/o3f6Ljgs/

**Comment by KacperMadej** [comment]
Another workaround - set CSS like in this demo: https://jsfiddle.net/BlackLabel/jh84sk16/

```css
@media screen and (-ms-high-contrast: active) {
   .highcharts-background { fill: none; }
}
```
