### ISSUE TITLE
Inconsistency in handling of states in styled mode

### ISSUE THREAD

**Issue by philipnye** [highcharts/highcharts#13518]
#### Expected behaviour
Setting `plotOptions.series.states.inactive.enabled` to `false` disables `inactive` state when in styled mode, so when one series is hovered over there is no change in appearance of the other series.

#### Actual behaviour
Setting `plotOptions.series.states.inactive.enabled` to `false` does not disable `inactive` state when in styled mode.

Your Black Label colleague has provided [a workaround](https://stackoverflow.com/questions/61693818/disabling-inactive-state-in-highcharts-styled-mode/61731069), but it seems inconsistent behaviour when `plotOptions.series.states.inactive.hover` can be disabled in this manner in styled mode. That's despite these two states being so closely related.

The documentation also makes no mention of it not working in styled mode.

#### Live demo with steps to reproduce
https://jsfiddle.net/philipnye/xhmf0qae/

#### Product version
Highcharts 8.1.0

#### Affected browser(s)
All

**Comment by pawelfus** [comment]
Hi @philipnye 

Thank you for reporting the issue. This is caused by default CSS styles that include styles for the inactive state. In CSS file (https://code.highcharts.com/css/highcharts.css) you can find: 
```css
.highcharts-point-inactive {
  opacity: 0.2;
  transition: opacity 50ms;
  /* quick in */
}

.highcharts-series-inactive {
  opacity: 0.2;
  transition: opacity 50ms;
  /* quick in */
}
```

There are no related styles for `highcharts-series-hover` state (showing marker is done in JS, not in CSS).

In other words, both states work the same way: states are adding `highcharts-series-STATENAME` class to the DOM, no matter the enabled/disabled property. The CSS snippet provided by @ppotaczek is not a workaround but a valid solution. My apologies for the inconvenience!
