### ISSUE TITLE
Ancestor div with a hidden visibility not hiding navigator and range selector

### ISSUE THREAD

**Issue by govinda18** [highcharts/highcharts#16901]
#### Expected behaviour
Ancestor div with a hidden visibility should hide navigator and range selector. This is useful when using Highcharts inside a tab which hides a tab content with visibility.

#### Actual behaviour
Ancestor div with a hidden visibility not hiding navigator and range selector

#### Live demo with steps to reproduce
http://jsfiddle.net/p6ugybj8/

#### Product version
Highstock JS v9.3.2

#### Affected browser(s)
Chrome

**Comment by raf18seb** [comment]
Hi @govinda18, thanks for creating the ticket!

Both navigator and range selector have (probably) unnecessary `visibility: visible;` styles applied. The defaults can be changed.

Workaround: disable them by CSS:
```css
.highcharts-range-selector-buttons > g {
	visibility: unset;
}

.highcharts-navigator {
	visibility: unset;
}
```

Demo: https://jsfiddle.net/BlackLabel/ps7z6txy/
