### ISSUE TITLE
Series options default colours are not valid

### ISSUE THREAD

**Issue by bholtbholt** [highcharts/highcharts#17051]
#### Expected behaviour
When I use the default settings in Highcharts
My graphs should have coloured points

#### Actual behaviour
The graphs are all black because the compiled CSS values are not valid CSS.

This is from `highcharts/css/highcharts.scss#279`:
```scss
/* Default colors */
@for $i from 1 through length($colors) {
  $color: nth($colors, $i);
  .highcharts-color-#{$i - 1} {
    fill: $color;
    stroke: $color;
  }
}
```

#### Live demo with steps to reproduce
This is what the CSS outputs:
```css
/* Series options */
/* Default colors */
.highcharts-color-0 {
  fill: "blue" #007bff;
  stroke: "blue" #007bff;
}

.highcharts-color-1 {
  fill: "indigo" #6610f2;
  stroke: "indigo" #6610f2;
}

…etc ("name" hex)
```

This is what it should output:
```css
.highcharts-color-0 {
  fill: #007bff;
  stroke: #007bff;
}

.highcharts-color-1 {
  fill: #6610f2;
  stroke: #6610f2;
}

…etc (hex only)
```
#### Product version
Highcharts 9.3.2
sass 1.38.0
webpack 4.46.0
css-loader 3.6.0
Bootstrap 4.5.3

#### Affected browser(s)
All -- it's a compiler issue.
