### ISSUE TITLE
Timeline chart: Wrong point-to-labelbox path color in styled mode

### ISSUE THREAD

**Issue by scebotari66** [highcharts/highcharts#17614]
#### Expected behaviour
In the [demo example for timeline chart](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-timeline/datetime-axis), the axis point matches the color of the path going to the label box. I would expect the same in styled mode.
![image](https://user-images.githubusercontent.com/329976/185113207-2981078a-566e-4745-95cc-82f284eddd73.png)

#### Actual behaviour
In styled mode the path color differs from the point color (it inherits from `.highcharts-color-0`). While there are color classes for the paths (e.g. `highcharts-data-label-color-1`), there are no style rules for these. The same issue is with bullet colors in the label box.
![image](https://user-images.githubusercontent.com/329976/185114038-b1a76cd5-d10e-44d2-be70-16e36b3a3fac.png)

#### Live demo with steps to reproduce
https://jsfiddle.net/scebotari66/1btx2wd3/

#### Product version
 Highcharts JS v10.2.0 (2022-07-05)

#### Affected browser(s)
All

**Comment by scebotari66** [comment]
For anyone having the same problem, I ended up generating the color rules for the `highcharts-data-label-color-` classes myself. Similarly to how `highcharts-color-` rules are generated in the default provided SCSS file.

```scss
@import '~highcharts/css/highcharts.scss';

// Fix path colors not matching point colors
@for $i from 1 through length($colors) {
  $color: nth($colors, $i);
  .highcharts-data-label-color-#{$i - 1} {
    fill: $color;
    stroke: $color;
  }
}
```
