### ISSUE TITLE
Inconsistent stacked column chart behavior after upgrading Highcharts from v10 to v11 - 0 value bars displayed

### ISSUE THREAD

**Issue by PinkChampagne17** [highcharts/highcharts#19069]
We have recently upgraded Highcharts from version 10 to 11 and observed an issue with stacked column charts which are inconsistent with version 10.

#### Expected behaviour
The bars corresponding to the 0 value don't display in the stacked columns chart.

#### Actual behaviour
When we use stacked columns with `chart.styledMode === true && yAxis.reversedStacks === false`, and on the top is a point that has 0 value then it's displayed anyway, even if explicitly assigning `plotOptions.minPointLength` to 0.

#### Live demo with steps to reproduce
The following two reproductions both use the same options.
(Bug occurring) V11: https://jsfiddle.net/027nxk3z/
(Expected) V10: https://jsfiddle.net/027nxk3z/1/

#### Product version
Highcharts v11.0.1

#### Affected browser(s)
Chrome 113.0.5672.126 (Official Build) (x86_64)

**Comment by karolkolodziej** [comment]
Hi, @PinkChampagne17!
Thank you for reporting the issue.

This issue is caused by CSS `stroke` here:
```CSS
.highcharts-color-1 {
    fill: var(--highcharts-color-1);
    stroke: var(--highcharts-color-1);
}
```

As a workaround, you can disable the `border` for the column- [demo](https://jsfiddle.net/BlackLabel/ocerxa6h/).

_Internal note:_
I was not able to bisect

**Comment by karolkolodziej** [comment]
@PinkChampagne17 You are right! 
In the case of the `styledMode` you can disable the border by CSS- [demo](https://jsfiddle.net/BlackLabel/jLp1uqmw/).
``` CSS
.highcharts-point {
  stroke-width: 0px !important;
}
```
