### ISSUE TITLE
Upgrading from 12.1.2 to 12.2.0 breaks `nullInteraction` on maps

### ISSUE THREAD

**Issue by jlherren** [highcharts/highcharts#23019]
#### Expected behaviour

Setting `nullInteraction: true` on highmaps should allow interaction with `null` values.

#### Actual behaviour

Countries with `null` values now have `opacity: 0` and are not visible anymore.

#### Live demo with steps to reproduce

Broken in 12.2.0: https://jsfiddle.net/vwg6yd9a/

Used to be fine in 12.1.2: https://jsfiddle.net/a85ydkfL/

#### Product version

Highmaps 12.2.0

#### Affected browser(s)

Chrome.

**Comment by jlherren** [comment]
Still broken in 12.3.0 and 12.4.0. Workaround:

```css
svg .highcharts-series path {
    /* Workaround for https://github.com/highcharts/highcharts/issues/23019 */
    opacity: 1;
}
```
