### ISSUE TITLE
Exporting button options - unable to use CSS

### ISSUE THREAD

**Issue by maheshjag** [highcharts/highcharts#4132]
http://jsfiddle.net/maheshjagadeesan/40kxz5k3/

In the above example, I'm trying to change the hover and select state colours of the context button's strokes, but I'm unable to.

Also, I can see in exporting.src.js that 'stroke-linecap' is hard-coded to 'round'.

**Comment by highslide-software** [comment]
If you can live with missing support in IE8, you can use CSS:
```css
.highcharts-button path {
    stroke-linecap: square;
}
.highcharts-button:hover path {
    stroke: white;
}
```
[View on jsFiddle](http://jsfiddle.net/40kxz5k3/2/).
