### ISSUE TITLE
Drillup event fires twice

### ISSUE THREAD

**Issue by rsmything** [highcharts/highcharts#5596]
Use chart with type 'column'

```
options:
    chart:
        events:
            drillup: (e) ->
                console.log e
```

![image](https://cloud.githubusercontent.com/assets/11719983/17751832/6afaf282-64e2-11e6-912a-190eca2747cb.png)
