### ISSUE TITLE
Text-align style property is not working in dataLabels

### ISSUE THREAD

**Issue by MarcAragones** [highcharts/highcharts#6282]
#### Expected behaviour
The text in the bubble's label should be centered.

#### Actual behaviour
The text is left aligned.

#### Live demo with steps to reproduce
http://jsfiddle.net/jzawgwef/10/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Thank you for reporting!

**Workaround:**
Use CSS:

```css
.highcharts-data-label span {
  text-align: center
}
```
Demo: http://jsfiddle.net/jzawgwef/11/

Or set this CSS inline: http://jsfiddle.net/jzawgwef/13/
