### ISSUE TITLE
Blurred content when rendering the tooltip in HTML while in styled mode

### ISSUE THREAD

**Issue by iacii** [highcharts/highcharts#7292]
I modified the styled mode demo by adding `tooltip: { useHTML: true }` to the options: [https://codepen.io/anon/pen/WZPQEm](https://codepen.io/anon/pen/WZPQEm)

If you hover over any of the slices, you'll notice the text is a little blurry.

I've narrowed it down to this CSS rule:

``` CSS
.highcharts-tooltip-0 {
    filter: url(#drop-shadow-0);
}
````

A possible second issue is `shadow: false` does not seem to have any effect when rendering the tooltip in styled mode.

I've verified this to be a problem in Firefox and Chrome.

**Comment by pawelfus** [comment]
Hi @iacii 

Thank you for reporting this issue. You can disable this shadow in CSS mode for example by setting:

```
div.highcharts-tooltip-0 {
  filter: none;
}
```

I think `div.highcharts-tooltip-0 { filter: none; }` should be added by default.

Regarding `shadow: false` - this doesn't have effect because it's set in CSS.

**Comment by iacii** [comment]
Okay, that makes sense. I solved it by adding this:

```` CSS
.highcharts-label.highcharts-tooltip { 
  filter: none; 
}
````

That catches `.highcharts-tooltip-x` where `x` is any integer.

Thanks!
