### ISSUE TITLE
Box Plot: Whiskers/Median appear on hover if their width is set to 0

### ISSUE THREAD

**Issue by sagargurtu** [highcharts/highcharts#7607]
#### Expected behaviour
For box plot charts, whiskers and median should not appear on hover when their widths are already set to 0.

#### Actual behaviour
In the below fiddle, hover on any box plot. Whiskers and Median appear.

#### Live demo with steps to reproduce
http://jsfiddle.net/h09psvn0/

#### Affected browser(s)
Chrome

**Comment by pawelfus** [comment]
Hi @sagargurtu 

Thank you for reporting this bug. It looks like `lineWidth` is applied on hover states, not `stemWidth`/`whiskerWidth`. 

**Workaround:**
Set line width in CSS:
```css
.highcharts-boxplot-median {
  stroke-width: 0;
}

.highcharts-boxplot-whisker {
  stroke-width: 0;
}
```

Demo: http://jsfiddle.net/h09psvn0/2/
