### ISSUE TITLE
Setting map navigation buttons text positions

### ISSUE THREAD

**Issue by anselmbradford** [highcharts/highcharts#9266]
I don't see a way via the API to position the text inside the map navigation buttons. I have these buttons:

<img width="57" alt="screen shot 2018-10-29 at 3 55 11 pm" src="https://user-images.githubusercontent.com/704760/47676461-11cb1f00-db93-11e8-8971-9d50e1fe1e11.png">

I can position them with:

```less
.highcharts-map-navigation text {
    transform: translate( 1px, -3px );
}
```

However, both buttons have the same parent CSS classes:

<img width="292" alt="screen shot 2018-10-29 at 3 53 55 pm" src="https://user-images.githubusercontent.com/704760/47676506-31624780-db93-11e8-8e64-56a9b9b3c183.png">

…so I don't see a good way to pick out the buttons individually. Each needs different adjustments so gets stuck at:

<img width="46" alt="screen shot 2018-10-29 at 3 57 08 pm" src="https://user-images.githubusercontent.com/704760/47676551-4ccd5280-db93-11e8-9d88-0e4bf33b62a6.png">

I can fix it with this incredibly awful hack:

```less
.highcharts-map-navigation text {
  transform: translate( 1px, -3px );
}

.highcharts-map-navigation[transform="translate(10,38)"] text {
  transform: translate( 5px, -4px );
}
```

<img width="45" alt="screen shot 2018-10-29 at 3 59 21 pm" src="https://user-images.githubusercontent.com/704760/47676665-9fa70a00-db93-11e8-8e7a-de882607d865.png">

It seems like highcharts should add custom CSS classes to each `.highcharts-map-navigation` node, to distinguish them, or is there another way I'm missing?

**Comment by anselmbradford** [comment]
Heeeey, well, staring at that I realized the zoom in button has `.highcharts-button-normal`, which the zoom out button does not have. But it still seems like they should each have specific classes.

**Comment by anselmbradford** [comment]
@KacperMadej Here's a [demo](http://jsfiddle.net/38bx5ufm/1/) showing that the styles can be adjusted for the buttons, breaking the layout.

**Comment by anselmbradford** [comment]
> The buttons could be adjusted using available API like in this demo: 

Could be, but that demo appears to be making larger buttons overall. I don't want larger buttons, I want a larger font size in the buttons, and when the font size is increased they don't lay out correctly.

**Comment by KacperMadej** [comment]
Padding could be used for further adjustments - http://jsfiddle.net/BlackLabel/q7jrsnh9/1/

**Comment by anselmbradford** [comment]
Ehhh seems pretty hackish with the negative padding, not to say it's not a nice hack! But it seems like those settings should go in CSS in styled mode (which I'm using).

**Comment by TorsteinHonsi** [comment]
I've added individual class names to the buttons now, so you can do something like this: http://jsfiddle.net/highcharts/q7jrsnh9/8/.

Also, already with the current version, you  should be able do style the item by [first-child or last-child selectors](https://www.w3schools.com/cssref/sel_firstchild.asp).

However, since this is SVG, I am not sure you'll get the results you want. The rectangle around the text will not respond to its size, `line-height` doesn't work, rectangle size and positioning can't be set through CSS. So maybe Kacper's solution is the best one after all.

**Comment by anselmbradford** [comment]
> Also, already with the current version, you should be able do style the item by first-child or last-child selectors.

I'm not sure why, but I'd tried first-child/last-child, and while:

```css
.highcharts-map-navigation {
    outline: 1px solid red;
}
```

Outlines the buttons

```css
.highcharts-map-navigation:first-child {
    outline: 1px solid red;
}
```

Does nothing.

> However, since this is SVG, I am not sure you'll get the results you want. The rectangle around the text will not respond to its size, line-height doesn't work, rectangle size and positioning can't be set through CSS. So maybe Kacper's solution is the best one after all.

I'm just aiming for 

```css
.highcharts-map-navigation.highcharts-zoom-in text {
  transform: translate( 1px, -3px );
}

.highcharts-map-navigation.highcharts-zoom-out text {
  transform: translate( 5px, -4px );
}
```

So that should be okay. It won't be correct in IE, but I'm okay for that at the moment.

**Comment by KacperMadej** [comment]
With current (6.2.0) version you could use CSS like:

```css
.highcharts-map-navigation text {
  fill: red;
}

.highcharts-map-navigation ~ .highcharts-map-navigation text {
  font-size: 32px;
  fill: green;
}
```

First sets style for both and second for all-but-first, so in this case for the second. Just reverse or override style from first in second if you don't want that option to be applied (like `fill` in the example above).
Demo: http://jsfiddle.net/BlackLabel/q7jrsnh9/10/
